#!/usr/bin/env php

<?php

use Hermes\Parser\ComposerWriter;
use Hermes\Parser\PackageWriter;

//function includeIfExists(string $file): bool
//{
//    return file_exists($file) && include $file;
//}
//
//if (
//    !includeIfExists(__DIR__ . '/../../../../autoload.php') &&
//    !includeIfExists(__DIR__ . '/../../vendor/autoload.php') &&
//    !includeIfExists(__DIR__ . '/../../../../../../vendor/autoload.php')
//) {
//    fwrite(STDERR, 'Install dependencies using Composer.' . PHP_EOL);
//    exit(1);
//}

require dirname(__DIR__) . '/vendor/autoload.php';

$arguments = getopt('cp', ['composer', 'package', 'path::', 'output::']);

if (isset($arguments['composer']) || isset($arguments['c'])) {
    (new ComposerWriter(($arguments['path'] ?? '.'), ($arguments['output'] ?? 'DEPENDENCIES')))->parse();
}

if (isset($arguments['package']) || isset($arguments['p'])) {
    (new PackageWriter(($arguments['path'] ?? ''), ($arguments['output'] ?? 'DEPENDENCIES')))->parse();
}

